
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # ??
    properties:
      hibernate:
        format_sql: true66
        show_sql: true
    defer-datasource-initialization: true

  redis:
    port: 6379
    host: 127.0.0.1

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer }
  secret-key: ${JWT_SECRET_KEY:happilyeverafterhappilyesdfghgdfsdsadfgfdsfgasdfjaskdfhasjkdfhasjkdfaskverafter}
  refresh-exp: ${JWT_REFRESH_EXP:123456789}
  access-exp: 360000

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace